# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rig < Formula
  desc "The most beautiful terminal radio CLI"
  homepage "https://github.com/MWhyte/rig"
  version "0.2.2"
  license "AGPL-3.0-only"

  depends_on "mpv"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MWhyte/rig/releases/download/v0.2.2/rig_darwin_amd64.tar.gz"
      sha256 "5012c512ca7324876d9e2403149f77a6e27d4aaa2dd3f943beeeb1c52788200b"

      define_method(:install) do
        bin.install "rig"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MWhyte/rig/releases/download/v0.2.2/rig_darwin_arm64.tar.gz"
      sha256 "ec92d9b79524e373fe5a95435efbb02f1f987c5d12915978cdb258124fbd68e2"

      define_method(:install) do
        bin.install "rig"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/MWhyte/rig/releases/download/v0.2.2/rig_linux_amd64.tar.gz"
      sha256 "a950536ecff77b680692f6c6feac10d09c6e015ba0ba02393babba8117bcd65f"
      define_method(:install) do
        bin.install "rig"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MWhyte/rig/releases/download/v0.2.2/rig_linux_arm64.tar.gz"
      sha256 "00a33b416ff2e8b53ad7ea5bd706c21fab906e67b720ea451e5b2811d89b410c"
      define_method(:install) do
        bin.install "rig"
      end
    end
  end
end
